config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks do
    member do
      get :save_for_later
    end
  end
  # get '/welcome', to: 'users#show'
  get 'tags/:tag', to: 'bookmarks#index', as: :tag



  get "home", to: 'welcome#index'
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    post '/users/sign_in', to: 'users/sessions#create'
    delete 'users/session', to: 'users/sessions#destroy'
  end

  resources :users, only: [:show, :index]

  as :user do
    authenticated :user do
      root 'users#show', as: '/'
    end
    unauthenticated :user do
      root 'users/sessions#new', as: "/"
    end
  end
  post 'add-amigo', to: "users#add_amigo"
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  has_and_belongs_to_many :users
    acts_as_taggable
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy, :save_for_later]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  def save_for_later
    save_bookmark_for_later
  end
  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        save_bookmark_for_later

        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }

      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
# Shows address
def website
  @address = Bookmark.address
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:address, :tag_list)
    end

    def save_bookmark_for_later
      current_user.bookmarks << @bookmark
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, local: true) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :bookmark_address %>
  </div>
  <div class="field">
    <%= form.label :tag_list, "Tags (separated by commas)" %>
    <%= form.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
          <td><%= link_to bookmark.address, bookmark.address %></td>
          <td><%= link_to("\xE2\x9D\xA4", save_for_later_bookmark_path(bookmark)) %></td>
          <td><%= link_to 'Show', bookmark %></td>
          <td><%= link_to('Edit', edit_bookmark_path(bookmark)) if user_signed_in? %></td>
          <td><%= link_to('Delete', bookmark, method: :delete, data: { confirm: 'Are you sure?' }) if user_signed_in? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @bookmark.address %>
  <h4>Tags:</h4>
  <ul>
  <% @bookmark.tags.each do |tag| %>
    <li><%= tag.name %></li>
  <% end %>
</ul>


</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>