config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks do
    member do
      get :save_for_later
    end
  end
  # get '/welcome', to: 'users#show'
  get 'tags/:tag', to: 'bookmarks#index', as: :tag



  get "home", to: 'welcome#index'
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_in', to: 'users/sessions#new'
    post '/users/sign_in', to: 'users/sessions#create'
    delete 'users/session', to: 'users/sessions#destroy'
  end

  resources :users, only: [:show, :index]

  as :user do
    authenticated :user do
      root 'users#show', as: '/'
    end
    unauthenticated :user do
      root 'users/sessions#new', as: "/"
    end
  end
  post 'add-amigo', to: "users#add_amigo"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BookmarkApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Antic|Raleway:400,800" rel="stylesheet">
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Bookmark Sharing App</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Friends", users_path  %></li>
            <li><%= link_to "\xE2\x9D\xA4", "#"  %></li>
            <% if user_signed_in? %>
              <li>
              <%= link_to('Logout', users_session_path, method: :delete) %>
             </li>
            <% else %>
              <li>
              <%= link_to('Login', omniauth_authorize_path(resource_name, provider))  %>
             </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!-- <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer class="panel panel default" id="copyright">
        <div class="panel-body">
          <p>&copy; Bookmark Sharing App - Christopher Hernandez and Adrian Martinez 2017</p><i class="fa fa-facebook-square fa-2x"aria-hidden="true"></i><i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i><i class="fa fa-github fa-2x" aria-hidden="true"></i>
        </div>
      </footer>
    </div> <!-- /container -->
  </body>
</html>